# ------------------------------------------------------------------------------
# update values to enable external connection 
# ------------------------------------------------------------------------------

external:
  enabled: true
  # type can be either NodePort or LoadBalancer
  type: LoadBalancer

## The StatefulSet Update Strategy which Kafka will use when changes are applied.
## ref: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies
updateStrategy:
  type: "RollingUpdate"
